const generator = require('generate-password');
const crypto = require('crypto');

class PasswordService {
  /**
   * Generate a secure random secret
   */
  generateSecureSecret(length = 32) {
    return crypto.randomBytes(length).toString('hex');
  }

  /**
   * Generate Jitsi-compatible secrets
   */
  generateJitsiSecrets() {
    return {
      jitsiSecret: this.generateSecureSecret(32),
      jwtSecret: this.generateSecureSecret(32),
      jwtAppId: `afyacare_${crypto.randomBytes(4).toString('hex')}`,
      turnSecret: this.generateSecureSecret(24)
    };
  }

  /**
   * Generate human-friendly but secure passwords
   */
  generateHumanReadable() {
    return generator.generate({
      length: 24,
      numbers: true,
      symbols: true,
      uppercase: true,
      strict: true
    });
  }

  /**
   * Generate all required config values for Jitsi
   */
  generateFullConfig() {
    return {
      // For your Express API .env
      api: {
        JWT_SECRET: this.generateSecureSecret(32),
        JWT_EXPIRY: '24h',
        RATE_LIMIT_WINDOW_MS: 900000,
        RATE_LIMIT_MAX_REQUESTS: 100
      },
      
      // For Jitsi Docker .env
      jitsi: {
        PUBLIC_URL: 'https://meet.yourcompany.com', // User will set this
        JITSI_IMAGE_VERSION: 'stable',
        JITSI_SECRET: this.generateSecureSecret(32),
        JWT_APP_SECRET: this.generateSecureSecret(32),
        JWT_APP_ID: `afyacare_${Date.now()}_${crypto.randomBytes(4).toString('hex')}`,
        ENABLE_LETSENCRYPT: 1,
        ENABLE_AUTH: 1,
        ENABLE_GUESTS: 1,
        AUTH_TYPE: 'jwt'
      },
      
      // For TURN server (optional but recommended)
      turn: {
        TURN_SECRET: this.generateSecureSecret(24),
        TURN_CREDENTIALS: this.generateHumanReadable()
      }
    };
  }

  /**
   * Generate .env file content for Jitsi Docker
   */
  generateJitsiEnvFile(config) {
    return `# Jitsi Meet Configuration - Generated by AfyaCare API
# Generated on: ${new Date().toISOString()}

# Public URL (REQUIRED - change this to your actual domain)
PUBLIC_URL=${config.PUBLIC_URL}

# Docker image version
JITSI_IMAGE_VERSION=${config.JITSI_IMAGE_VERSION}

# Network configuration
HTTP_PORT=8000
HTTPS_PORT=8443

# Security secrets (AUTO-GENERATED - Save these securely)
JITSI_SECRET=${config.JITSI_SECRET}
JWT_APP_SECRET=${config.JWT_APP_SECRET}
JWT_APP_ID=${config.JWT_APP_ID}

# Authentication
ENABLE_AUTH=${config.ENABLE_AUTH}
ENABLE_GUESTS=${config.ENABLE_GUESTS}
AUTH_TYPE=${config.AUTH_TYPE}

# SSL (Let's Encrypt)
ENABLE_LETSENCRYPT=${config.ENABLE_LETSENCRYPT}
LETSENCRYPT_DOMAIN=${config.PUBLIC_URL.replace('https://', '').replace('http://', '')}
LETSENCRYPT_EMAIL=admin@${config.PUBLIC_URL.replace('https://', '').replace('http://', '')}

# TURN server (for better connectivity)
TURN_HOST=turn.${config.PUBLIC_URL.replace('https://', '').replace('http://', '')}
TURN_PORT=3478
TURN_SECRET=${config.TURN_SECRET}

# Performance
ENABLE_OCTO=1
VIDEOBRIDGE_MAX_BITRATE=0
JVB_ADVERTISE_IPS=private

# Debug (set to 0 in production)
DEBUG=0
`;
  }

  /**
   * Generate docker-compose override for your API to work with Jitsi
   */
  generateDockerComposeOverride(config) {
    return `version: '3.8'

services:
  # Your existing API service with Jitsi config
  api:
    environment:
      - JITSI_HOST=jitsi-web
      - JITSI_PORT=8443
      - JITSI_SECRET=${config.jitsi.JITSI_SECRET}
      - JWT_SECRET=${config.api.JWT_SECRET}
      - JWT_APP_ID=${config.jitsi.JWT_APP_ID}
      - JWT_APP_SECRET=${config.jitsi.JWT_APP_SECRET}
    depends_on:
      - jitsi-web
      - jitsi-prosody
      - jitsi-jicofo
      - jitsi-jvb

  # Add healthcheck for Jitsi services
  jitsi-web:
    healthcheck:
      test: ["CMD", "curl", "-f", "https://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  jitsi-prosody:
    healthcheck:
      test: ["CMD", "prosodyctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
`;
  }
}

module.exports = new PasswordService();